matrix:
  include:
  - language: node_js
    sudo: false
    node_js:
    - "8.12"
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - npm run build

  - language: java
    jdk: oraclejdk8
    before_install:
    - chmod +x backend/gradlew
    script:
    - ./backend/gradlew check --project-dir backend