image: gitpod/workspace-full
tasks:
  - init: cd frontend; npm install; cd ../backend; ./gradlew build
    command: cd ../frontend; npm run start; cd ../backend; ./gradlew run
ports:
  - port: 4567
  - port: 8080
    onOpen: open-preview
  - port: 9998
  - port: 9999