image: gitpod/workspace-full
tasks:
  - init: cd frontend; npm install
    command: cd frontend; npm run start 
    command: cd backend; ./gradlew run
ports:
  - port: 4567
  - port: 4200
    onOpen: open-preview
  - port: 9998
  - port: 9999