image: gitpod/workspace-full
tasks:
  - init: cd frontend; npm install; cd ../backend; ./gradlew build
    command: npm run start; ./gradlew run
ports:
  - port: 4567
  - port: 8080
  - port: 9998
  - port: 9999
    onOpen: open-preview